<?php

namespace Asi\ClinicaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClinicaRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClinicaRepository extends EntityRepository
{



}