<?php

namespace Asi\ClinicaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DetallefacturaRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetallefacturaRepository extends EntityRepository
{

    public function findByServicioAndFactura($servicio, $factura)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT df FROM AsiClinicaBundle:Detallefactura df WHERE df.idservicio = :servicio AND df.idfactura = :factura')
            ->setParameter("servicio", $servicio)
            ->setParameter("factura", $factura)
            ->getOneOrNullResult();
    }

    public function findExamenesByFactura($factura)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT df FROM AsiClinicaBundle:Detallefactura df INNER JOIN AsiClinicaBundle:Servicio se WHERE df.idservicio = se.id INNER JOIN AsiClinicaBundle:Tiposervicio ts WHERE se.idtiposervicio = ts.id AND ts.nombre = \'Examen\' AND df.idfactura = :factura')
            ->setParameter("factura", $factura)
            ->getResult();
    }

    public function findExamenesRecetadosByFactura($factura)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT df FROM AsiClinicaBundle:Detallefactura df INNER JOIN AsiClinicaBundle:Servicio se WHERE df.idservicio = se.id INNER JOIN AsiClinicaBundle:Tiposervicio ts WHERE se.idtiposervicio = ts.id AND ts.nombre = \'Examen\' AND df.idfactura = :factura AND df.facturado = 0')
            ->setParameter("factura", $factura)
            ->getResult();
    }

    public function findMedicamentosByFactura($factura)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT df FROM AsiClinicaBundle:Detallefactura df INNER JOIN AsiClinicaBundle:Servicio se WHERE df.idservicio = se.id INNER JOIN AsiClinicaBundle:Tiposervicio ts WHERE se.idtiposervicio = ts.id AND ts.nombre = \'Medicamento\' AND df.idfactura = :factura')
            ->setParameter("factura", $factura)
            ->getResult();
    }

    public function findMedicamentosRecetadosByFactura($factura)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT df FROM AsiClinicaBundle:Detallefactura df INNER JOIN AsiClinicaBundle:Servicio se WHERE df.idservicio = se.id INNER JOIN AsiClinicaBundle:Tiposervicio ts WHERE se.idtiposervicio = ts.id AND ts.nombre = \'Medicamento\' AND df.idfactura = :factura AND df.facturado = 0')
            ->setParameter("factura", $factura)
            ->getResult();
    }

}