<?php

namespace Asi\ClinicaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DisponibilidadRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisponibilidadRepository extends EntityRepository
{


	public function findByIdclinicaAndFechaFutura($idclinica)
    {
        $fecha = new \DateTime('today');
        $horas = new \DateInterval('PT24H');
        $fecha->add($horas);

        return $this->getEntityManager()
            ->createQuery('SELECT d FROM AsiClinicaBundle:Disponibilidad d WHERE d.idclinica = :idclinica AND (d.fecha > :fecha OR (d.fecha = :fecha AND d.hora > :hora)) ORDER BY d.fecha, d.hora ASC')
            ->setParameter("idclinica", $idclinica)
            ->setParameter("fecha", $fecha)
            ->setParameter("hora", new \DateTime('now'))
            ->getResult();
    }

    public function findByClinicasAndFechaFutura($clinicas)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT d FROM AsiClinicaBundle:Disponibilidad d WHERE d.idclinica IN (:clinicas) AND (d.fecha >= :fecha) ORDER BY d.fecha, d.hora ASC')
            ->setParameter("clinicas", $clinicas)
            ->setParameter("fecha", new \DateTime('today'))
            ->getResult();
    }


}