<?php

namespace Asi\ClinicaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EspecialidadRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EspecialidadRepository extends EntityRepository
{


    public function findEspecialidadDisponible()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT DISTINCT e.id, e.nombre FROM AsiClinicaBundle:Especialidad e INNER JOIN AsiClinicaBundle:Clinica c WHERE e.id = c.idespecialidad')
            ->getResult();
    }


}