<?php

namespace Asi\ClinicaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExamenRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamenRepository extends EntityRepository
{

    public function cantidadExamenes()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT COUNT(e.id) FROM AsiClinicaBundle:Examen e')
            ->getSingleResult();
    }

}