<?php

namespace Asi\ClinicaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InmunizacionRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InmunizacionRepository extends EntityRepository
{

	public function findByInmunizacionAndIdConsulta($inmunizacion, $consulta)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT im FROM AsiClinicaBundle:inmunizacion im WHERE im.id = :inmunizacion AND im.idconsulta = :consulta')
            ->setParameters(array("inmunizacion" => $inmunizacion, "consulta" => $consulta))
            ->getOneOrNullResult();
    }

    public function consultaTieneInmunizaciones($consulta)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT COUNT(im) FROM AsiClinicaBundle:Inmunizacion im WHERE im.idconsulta = :consulta')
            ->setParameter("consulta", $consulta)
            ->getOneOrNullResult();
    }

}