<?php

namespace Asi\ClinicaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ItemexamenfisicoRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemexamenfisicoRepository extends EntityRepository
{


    public function findItemsByEspecialidad($especialidad)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT DISTINCT i FROM AsiClinicaBundle:Itemexamenfisico i INNER JOIN AsiClinicaBundle:Itemespecialidad ie WHERE (ie.iditemexamenfisico = i.id OR i.universal = TRUE) AND ie.idespecialidad IN (:especialidad)')
            ->setParameter("especialidad", $especialidad)
            ->getResult();
    }

}