<?php

namespace Asi\ClinicaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MedicamentoRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicamentoRepository extends EntityRepository
{

    public function cantidadMedicamentos()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT COUNT(m.id) FROM AsiClinicaBundle:Medicamento m')
            ->getSingleResult();
    }

}