<?php

namespace Asi\ClinicaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PacienteRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PacienteRepository extends EntityRepository
{

	public function findAllByClinicas($clinicas)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM AsiClinicaBundle:Paciente p INNER JOIN AsiClinicaBundle:Cita c WHERE p.id = c.idpaciente INNER JOIN AsiClinicaBundle:Disponibilidad d WHERE c.idDisponibilidad = d.id INNER JOIN AsiClinicaBundle:Clinica cl WHERE d.idclinica = cl.id INNER JOIN AsiClinicaBundle:Personalclinica pcl WHERE pcl.idclinica = cl.id AND pcl IN(:clinicas)')
            ->setParameter("clinicas", $clinicas)
            ->getResult();
    }

   	public function findOneByClinicasAndPaciente($clinicas, $paciente)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM AsiClinicaBundle:Paciente p INNER JOIN AsiClinicaBundle:Cita c WHERE p.id = c.idpaciente INNER JOIN AsiClinicaBundle:Disponibilidad d WHERE c.idDisponibilidad = d.id INNER JOIN AsiClinicaBundle:Clinica cl WHERE d.idclinica = cl.id INNER JOIN AsiClinicaBundle:Personalclinica pcl WHERE pcl.idclinica = cl.id AND pcl IN(:clinicas) AND p.id = :paciente')
            ->setParameter("clinicas", $clinicas)
            ->setParameter("paciente", $paciente)
            ->getOneOrNullResult();
    }

}