<?php

namespace Asi\ClinicaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PatologiaRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatologiaRepository extends EntityRepository
{


    public function cantidadPatologias()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT COUNT(p.id) FROM AsiClinicaBundle:Patologia p')
            ->getSingleResult();
    }

}