<?php

namespace Asi\ClinicaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonalclinicaRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonalclinicaRepository extends EntityRepository
{

    public function findByPersonalAndClinica($personal, $clinica)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT pc FROM AsiClinicaBundle:Personalclinica pc INNER JOIN AsiClinicaBundle:Personal pe WHERE pc.idpersonal = pe.id INNER JOIN AsiClinicaBundle:Medico me WHERE me.idpersonal = pe.id AND pc.idpersonal = :personal AND pc.idclinica = :clinica')
            ->setParameter("personal", $personal)
            ->setParameter("clinica", $clinica)
            ->getOneOrNullResult();
    }

}