<?php

namespace Asi\ClinicaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ServicioRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicioRepository extends EntityRepository
{

    public function findExamenesNotInFactura($factura)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT se FROM AsiClinicaBundle:Servicio se INNER JOIN AsiClinicaBundle:Tiposervicio ts WHERE se.idtiposervicio = ts.id AND ts.nombre = \'Examen\' AND se.id NOT IN(SELECT IDENTITY(df.idservicio) FROM AsiClinicaBundle:Detallefactura df WHERE df.idfactura = :factura)')
            ->setParameter("factura", $factura)
            ->getResult();
    }

    public function findMedicamentosNotInFactura($factura)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT se FROM AsiClinicaBundle:Servicio se INNER JOIN AsiClinicaBundle:Tiposervicio ts WHERE se.idtiposervicio = ts.id AND ts.nombre = \'Medicamento\' AND se.id NOT IN(SELECT IDENTITY(df.idservicio) FROM AsiClinicaBundle:Detallefactura df WHERE df.idfactura = :factura)')
            ->setParameter("factura", $factura)
            ->getResult();
    }

}