<?php

namespace Asi\ClinicaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VacunaRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VacunaRepository extends EntityRepository
{

	public function findVacunasNotInConsulta($consulta)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT v FROM AsiClinicaBundle:Vacuna v WHERE v.id NOT IN (SELECT va.id FROM AsiClinicaBundle:Vacuna va INNER JOIN AsiClinicaBundle:Inmunizacion im WHERE im.idvacuna = va.id AND im.idconsulta = :consulta)')
            ->setParameter("consulta", $consulta)
            ->getResult();
    }

    public function cantidadVacunas()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT COUNT(v.id) FROM AsiClinicaBundle:Vacuna v')
            ->getSingleResult();
    }

}